version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"